### ISSUE TITLE
Off-by-one bug in calculation of zeros in SparseHll::toDense 

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/airlift#42]
I noticed a bug in SparseHll::toDense while porting HLL algorithm to C++. 

https://github.com/airlift/airlift/blob/master/stats/src/main/java/io/airlift/stats/cardinality/SparseHll.java#L175

Here, decodeBucketValue has the number of zeros + 1, hence, the  +1 in `listener.visit(bucket, zeros + 1);` will add an extra one.

See https://github.com/airlift/airlift/issues/926

CC: @arhimondr @rongrong @tdcmeehan @highker

**Comment by rongrong** [comment]
Do we understand the implications of this in correctness in production?

**Comment by jonhehir** [comment]
This issue is a little old, but I think I believe it's not an issue (anymore?). I cleaned up the `toDense()` function a little bit and added tests in #54, and it seems to be recording the right numbers.

**Comment by jonhehir** [comment]
Per the unit tests in #55, it seems the correct values are being recorded.
