### ISSUE TITLE
Support build on Java 11

### ISSUE THREAD

**Issue by dnskr** [prestodb/airlift#79]
### Problem
Current implementation does not allow to build project using Java 11.

### Issue 1
Module `stats` has missing dependency:
```xml
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
        </dependency>
```
**Solution**: Add missing dependency.

### Issue 2
Module `jmx` uses `sun.management.Agent` class in `com.facebook.airlift.jmx.JmxAgent8`:
https://github.com/prestodb/airlift/blob/88c682a03589658e8e0b61f629dee2e3c2b1039c/jmx/src/main/java/com/facebook/airlift/jmx/JmxAgent8.java#L20-L22
**Solution**: cherry-pick https://github.com/airlift/airlift/commit/cb70a835858d6a823f39989916d75dee09af5930 or implement similar solution.

**Comment by rschlussel** [comment]
also let's add another github actions for java 11 so we don't break it again.
